### ISSUE TITLE
Uncaught SyntaxError

### ISSUE THREAD

**Issue by diboma** [pjprijs/library#2]
I get this error:
```
Uncaught SyntaxError: expected expression, got '<'
    jQuery 8
        b
        globalEval
        text script
        s
        l
        o
        send
        ajax
    doLoad http://localhost/bib/scripts/init.js?rnd=799530374:122
    <anonymous> http://localhost/bib/scripts/initDefault.js?rnd=1381052180:3
    jQuery 13
        e
        t
        setTimeout handler*Deferred/then/l/<
        c
        fireWith
        fire
        c
        fireWith
        ready
        B
        EventListener.handleEvent*
        <anonymous>
        <anonymous>
```

**Comment by pjprijs** [comment]
What's the output of: 'http://localhost/bib/php/init.php' (check network tab in developer tools)?

_I'm still developing the software by the way, this is the first release (with a lot of features still missing), but it should work.
I put this release via git clone on my raspberry pi last week, and worked without issues._

**Comment by pjprijs** [comment]
I just uploaded a test version to my server: https://library.pjprijs.nl/
When I don't set the right credentials for the database, I get the same error.

Did you run the SQL scripts on your database (first the tables and the extra script as last)?

**Comment by diboma** [comment]
The output of 'http://localhost/bib/php/init.php' is:
`Not Found
The requested URL was not found on this server.`

The Network Tab and the console mention: 
`404 init.php not found`
(since there is no init.php file in the php-folder)

I successfully ran all SQL scripts. 

The error seems to be shorter but is still there:
`Uncaught SyntaxError: expected expression, got '<'
    jQuery 6
        b
        globalEval
        text script
        s
        l
        o
bib:1
`

**Comment by pjprijs** [comment]
Sorry, my bad, forgot to check.
I meant 'ajax/init.php'

**Comment by diboma** [comment]
Thanks for that. Following the output of "ajax.init.php", I found out that I had placed the config.php file in the root folder, not in the php folder. Putting it in the php folder resolved the error.

**Comment by pjprijs** [comment]
Issue solved
